### ISSUE TITLE
Manglende modul ved installation på Mac OS X

### ISSUE THREAD

**Issue by pellegoeg** [Kortforsyningen/Qgis_plugin_Kortforsyningen#48]
Af manglende sted at indberette bugs, så får i den her.

Jeg er klar over kodebasen til qgis3 ligger i et andet repos, men via plugin downloaderen i QGIS 3 så får jeg nedestående fejl. Et hurtigt overblik, så ønsker den bagkompabilitets pakken future, men denne eksistere (ihverfald som standard) ikke i python 3.6 og bør ikke være nødvendig, så et tjek for python version og så undlade import af modulet burde kunne rette op på nedestående fejl.

QGIS 3 installeret via http://www.kyngchaos.com/  på mac os x high sierra

´´´
Couldn't load plugin 'Kortforsyningen' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/prg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Kortforsyningen/__init__.py", line 34, in classFactory
    from .kortforsyningen import Kortforsyningen
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/prg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Kortforsyningen/kortforsyningen.py", line 45, in 
    from .qlr_file import QlrFile
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/prg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Kortforsyningen/qlr_file.py", line 1, in 
    from future import standard_library
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'

Python version: 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.0.0-Girona Girona, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/prg/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/prg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/prg/Library/Application Support/QGIS/QGIS3/profiles/default/python
´´´

**Comment by DocDemar** [comment]
Issue flyttet til
https://github.com/Kortforsyningen/Qgis_plugin_Kortforsyningen_v3/issues/11
